version: '3'

services:
  web:
    build: .
    ports:
      - 3000:3000
    links:
      - pg
    environment:
      DATABASE_URL: "postgres://postgres:postgres@pg:5432/postgres?sslmode=disable"
      PORT: 3000
    command: ["./wait-for-it.sh", "pg:5432", "--", "./dtn-server"]

  pg:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"